config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :show]

  resource :session, only: [:create, :new, :destroy]

  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, only: [:create, :edit, :show, :update, :destroy] do
    resources :tracks, only: [:new]
  end

  resources :tracks, only: [:create, :edit, :show, :update, :destroy]

end

app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  band_id    :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Album < ActiveRecord::Base
  belongs_to :band

  has_many :tracks,
    dependent: :destroy
end

app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :integer          not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Band < ActiveRecord::Base
  has_many :albums,
    dependent: :destroy

  has_many :tracks,
    through: :albums,
    source: :tracks
end

app/models/track.rb
# == Schema Information
#
# Table name: tracks
#
#  id         :integer          not null, primary key
#  title      :string
#  album_id   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Track < ActiveRecord::Base
  belongs_to :album

  has_one :band,
    through: :album,
    source: :band
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  validates :email, :session_token, presence: true, uniqueness: true
  validates :password_digest, presence: true
  validates :password, length: { minimum: 6 }, allow_nil: true

  after_initialize :ensure_session_token

  attr_reader :password

  def self.find_by_credentials(email, password)
    user = self.find_by(email: email)
    return nil unless user
    user.is_password?(password) ? user : nil
  end

  def self.generate_session_token
    SecureRandom.urlsafe_base64(16)
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
    self.session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  private
  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :require_user!

  def new
    @band = Band.find(params[:band_id])
    @album = Album.new(band_id: params[:band_id])
    render :new
  end

  def create
    @album = Album.new(album_params)
    if @album.save
      redirect_to album_url(@album)
    else
      @band = @album.band
      flash[:errors] = @album.errors.full_messages
      render :new
    end
  end

  def edit
    @album = Album.find(params[:id])
    render :edit
  end

  def show
    @album = Album.find(params[:id])
    render :show
  end

  def update
    @album = Album.find(params[:id])
    if @album.update(album_params)
      redirect_to album_url(@album)
    else
      flash[:errors] = @album.errors.full_messages
      redirect_to edit_album_url(@album)
    end
  end

  def destroy
    album = Album.find(params[:id])
    album.destroy
    redirect_to band_url(album.band_id)
  end

  private
  def album_params
    album_params = params.require(:album).permit(:band_id, :title, :year, :live)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def log_in_user!(user)
    user.reset_session_token!
    session[:session_token] = user.session_token
  end

  def logout
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def logged_in?
    !!current_user
  end

  def already_logged_in
    if logged_in?
      current_user.errors[:already] << "logged in!"
      flash[:errors] = current_user.errors.full_messages
      redirect_to root_url
    end
  end

  def require_user!
    redirect_to new_session_url if current_user.nil?
  end
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :require_user!

  def index
    @bands = Band.all
    render :index
  end

  def show
    @band = Band.find(params[:id])
    render :show
  end

  def new
    @band = Band.new
    render :new
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      redirect_to bands_url
    else
      flash[:errors] = @band.errors.full_messages
      redirect_to new_band_url
    end
  end

  def edit
    @band = Band.find(params[:id])
    render :edit
  end

  def update
    @band = Band.find(params[:id])
    if @band.update(band_params)
      redirect_to band_url(@band)
    else
      flash[:errors] = @band.errors.full_messages
      redirect_to edit_track_url
    end
  end

  def destroy
    band = Band.find(params[:id])
    band.destroy
    redirect_to bands_url
  end

  private
  def band_params
    params.require(:band).permit(:name)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  before_action :already_logged_in, only: :new

  def new
    @params = params
    render :new
  end

  def create
    @user = User.find_by_credentials(params[:user][:email], params[:user][:password])
    if @user
      log_in_user!(@user)
      redirect_to user_url(@user)
    else
      flash[:errors] = ["invalid credentials"]
      redirect_to new_session_url
    end
  end

  def destroy
    logout
    redirect_to bands_url
  end

end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :require_user!

  def new
    @album = Album.find(params[:album_id])
    @track = Track.new(album_id: params[:album_id])
  end

  def create
    @track = Track.new(track_params)
    if @track.save
      redirect_to track_url(@track)
    else
      @album = @track.album
      flash[:errors] = @track.errors.full_messages
      render :new
    end
  end

  def edit
    @track = Track.find(params[:id])
    render :edit
  end

  def show
    @track = Track.find(params[:id])
    render :show
  end

  def update
    @track = Track.find(params[:id])
    if @track.update(track_params)
      redirect_to track_url(@track)
    else
      flash[:errors] = @album.errors.full_messages
      redirect_to edit_track_url(@track)
    end
  end

  def destroy
    track = Track.find(params[:id])
    track.destroy
    redirect_to album_url(album.band_id)
  end

  private
  def track_params
    track_params = params.require(:track).permit(:album_id, :title, :ord, :bonus, :lyrics)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @params = params
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in_user!(@user)
      redirect_to user_url(@user)
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to new_user_url
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token
    '<input type="hidden" name="authenticity_token" value="#{form_authenticity_token}">'.html_safe
  end
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/_form.html.erb
<% action = (album.persisted? ? album_url(album) : albums_url) %>
<% method = (album.persisted? ? :patch : :post) %>

<form action="<%= action %>" method="post">
  <%= auth_token %>
  <input type="hidden" name="_method" value="<%= method %>">

  <label for="title">Title</label>
  <input type="text" name="album[title]" id = "title" value="<%= album.title %>">

  <br>

  <label for="year">Year</label>
  <select name="album[year]" value="<%= album.year %>">
    <option value="Select Year" disabled = "true" <%= album.year ? "" : "Selected" %> >Select Year</option>
    <% (Date.today.year).downto(1925) do |year| %>
      <option value="<%= year %>" <%= album.year == year ? "selected" : ""  %> >
        <%= year %>
      </option>
    <% end %>
  </select>
  <br>

  <label for="band">Band</label>
  <select name="album[band_id]" id="band">
    <% Band.all.each do |band| %>
      <option
      <%= band.id == album.band_id ? "selected" : "" %>
        value="<%= band.id %>">
        <%= band.name %>
    </option>
    <% end %>
  </select>

  <br>

  <input type="radio" name="album[live]" id="studio_album" value="false" <%= album.live ? "" : "checked" %>>
  <label for="studio_album">Studio Album</label>
  <input type="radio" name="album[live]" id="live_album" value="true" <%= album.live ? "checked" : "" %>>
  <label for="live_album">Live Album</label>

  <br>

  <% submit_text = (album.persisted? ? 'Update' : 'New') + ' album' %>

  <input type="submit" value="<%= submit_text %>">
</form>

app/views/albums/edit.html.erb
<h1>Edit Album</h1>

<%= render 'form', album: @album %>

<%= button_to("Back to #{@album.title}", album_url(@album), method: :get) %>

app/views/albums/new.html.erb
<h1>Add Album</h1>

<%= render 'form', album: @album %>

<%= button_to("Back to #{@band.name}", band_url(@band), method: :get) %>

app/views/albums/show.html.erb
<h1><%= @album.title %></h1>
<h2><%= @album.band.name %></h2>
<h4><%= @album.year %></h4>
<h4><%= @album.live ? "Live album" : "Studio album" %></h4>

<body>
  <h4>Tracks</h4>
  <% @album.tracks.each do |track| %>
     <%= track.ord %>. <a href="../tracks/<%= track.id %>"><%= track.title %> <br></a>
  <% end %>
</body>

<br>

<%= button_to("Back to #{@album.band.name}", band_url(@album.band), method: :get) %>
<%= button_to("Add track", new_album_track_url(@album), method: :get) %>
<%= button_to("Edit album", edit_album_url, method: :get) %>
<%= button_to("Delete album", album_url, method: :delete) %>

app/views/bands/_form.html.erb
<% action = (band.persisted? ? band_url(band) : bands_url) %>
<% method = (band.persisted? ? :patch : :post) %>

<form action="<%= action %>" method="post">
  <%= auth_token %>
  <input type="hidden" name="_method" value="<%= method %>">

  <label for="band_name">Band Name</label>
  <input
    type="text"
    name="band[name]"
    id ="band_name"
    value="<%= band.name %>">

  <br>


  <% submit_text = (band.persisted? ? 'Update' : 'New') + ' band' %>
  <input type="submit" value="<%= submit_text %>">
</form>

app/views/bands/edit.html.erb
<h1>Edit Band</h1>

<%= render 'form', band: @band %>

<%= button_to("Back to #{@band.name}", bands_url, method: :get) %>

app/views/bands/index.html.erb
<header>
  <h1>All Bands</h1>
  <!-- <img src="http://timesofindia.indiatimes.com/photo/45533362.cms"> -->
</header>

<body>
<ul>
  <% @bands.each do |band| %>
    <li> <%= link_to band.name, band_url(band) %> </li>
  <% end %>
</ul>
</body>

<%= link_to "New band", new_band_url %>

app/views/bands/new.html.erb
<h1>New Band</h1>

<%= render 'form', band: @band %>

<%= button_to("Back to Bands", bands_url, method: :get) %>

app/views/bands/show.html.erb
<h1> <%= @band.name %> </h1>

<body>
  <h4>Albums</h4>
  <% @band.albums.each do |album| %>
    <a href="../albums/<%= album.id %>"> <%= album.title %> <%= album.year %> <br> </a>
  <% end %>
</body>

<br>

<%= button_to("All Bands", bands_url, method: :get) %>
<%= button_to("Add album", new_band_album_url(@band), method: :get) %>
<%= button_to("Edit band", edit_band_url, method: :get) %>
<%= button_to("Delete band", band_url, method: :delete) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicApp</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>

<header>
  <% if current_user %>
    <%= button_to("Logout", session_url, method: :delete)  %>
  <% else %>
    <%= button_to("Login", new_session_url, method: :get) %>
    <%= button_to("Sign up", new_user_url, method: :get) %>
  <% end %>
</header>

<%= render 'shared/errors'%>


<body>
<%= yield %>

</body>
</html>

app/views/shared/_errors.html.erb
<% if flash[:errors] %>
  <ul>
    <% flash[:errors].each do |error| %>
      <li> <%= error %> </li>
    <% end %>
  </ul>
<% end %>

app/views/shared/_login_signup_form.html.erb
<% action = @params[:controller] == "users" ? users_url : session_url %>

<form action="<%= action %>" method="post">
  <%= auth_token %>

  <label for="email">Email</label>
  <input type="text" name="user[email]" id="email">

  <label for="password">Password</label>
  <input type="password" name="user[password]" id="password">

  <input type="submit" value="Submit">
</form>

app/views/tracks/_form.html.erb
<% action = (track.persisted? ? track_url(track) : tracks_url) %>
<% method = (track.persisted? ? :patch : :post) %>

<form action="<%= action %>" method="post">
  <%= auth_token %>
  <input type="hidden" name="_method" value="<%= method %>">

  <label for="title">Title</label>
  <input type="text" name="track[title]" id = "title" value="<%= track.title %>">

  <br>

  <% albums = track.band.albums %>
  <label for="album">Album</label>
  <select name="track[album_id]" id="album">
    <% albums.each do |album| %>
      <option
      <%= album.id == track.album_id ? "selected" : "" %>
      value="<%= album.id %>">
        <%= album.title %>
      </option>
    <% end %>
  </select>

  <br>

  <label for="track_number">Track Number</label>
  <input type="integer"
        name="track[ord]"
        value="<%= track.ord %>"
        id = "track_number"
        maxlength="4"
        size="4">

  <br>

  <input type="radio" name="track[bonus]" value="false" id="regular"
          <%= track.bonus ? "" : "checked" %>>
  <label for="regular">Regular Track</label>
  <input type="radio" name="track[bonus]" value="true" id="bonus"
          <%= track.bonus ? "checked" : "" %>>
  <label for="bonus">Bonus Track</label>

  <br>

  <label for="lyrics">Lyrics</label>
  <br>
  <textarea id = "lyrics" name="lyrics" rows="8" cols="80"><%= track.lyrics %></textarea>

  <br>

  <% submit_text = (track.persisted? ? 'Update' : 'New') + ' track' %>

  <input type="submit" value="<%= submit_text %>">
</form>

app/views/tracks/edit.html.erb
<h1>Edit Track</h1>

<%= render 'form', track: @track %>

<%= button_to("Back to #{@track.title}", track_url(@track), method: :get) %>

app/views/tracks/new.html.erb
<h1>New Track</h1>

<%= render 'form', track: @track %>

<%= button_to("Back to #{@album.title}", album_url(@album), method: :get) %>

app/views/tracks/show.html.erb
<h1><%= @track.title %></h1>
<h2> <%= @track.album.title %> - <%= @track.band.name %></h2>
<h4>Track No. <%=  @track.ord %></h4>
<%= "Bonus Track" if @track.bonus %>

<br>
<h4>Lyrics</h4>
<%= @track.lyrics %>
<br>

<%= button_to("Back to #{@track.album.title}", album_url(@track.album), method: :get) %>
<%= button_to("Edit track", edit_track_url, method: :get) %>
<%= button_to("Delete track", track_url, method: :delete) %>

app/views/users/new.html.erb
<head>
  <h1>Sign up!</h1>
</head>

<%= render "shared/login_signup_form" %>

app/views/users/show.html.erb
<%= button_to("Go to Bands", bands_url, method: :get) %>

<body>
  <img src="https://cdn.meme.am/cache/instances/folder379/500x/75680379.jpg" title="There is no chance to survive, make your time">
</body>